# Generated by Django 4.0.3 on 2022-04-05 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TODO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=64)),
                ('secondName', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField()),
                ('emailAddress', models.CharField(max_length=64)),
                ('phoneNumber', models.CharField(max_length=64)),
                ('contactType', models.CharField(max_length=64)),
                ('is_complete', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
