# Generated by Django 4.0.3 on 2022-04-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='contactType',
            new_name='contactTypeOne',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='phoneNumber',
            new_name='phoneNumberOne',
        ),
        migrations.AddField(
            model_name='todo',
            name='contactTypeThree',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='contactTypeTwo',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='phoneNumberTwo',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
